### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by hippyau** [hippyau/rnc#1]
- [x] UI to select relevant .txt file for editing
- [x] Use a directory of files from the node, rather than hard-code file names
- [x] Send JSON back to node
- [x] Send reboot command
- [ ] Special handling of rconfig.txt to avoid user disabling remote config by accident.
- [ ] Special treatment when node IP / netmask is changed in network.txt.... Reboot then remove from list, wait a sec, search for new IP 
- [x] Discovery of nodes, use mDNS
- [x] Colour Picker
- [x] iOS / MacOS builds
- [x] Use a dark theme
- [x] Search screen
- [ ] Handle "Display Udf"  Device physical display user defined formatting
- [x] Show local IP's
- [x] UDP Realtime Messages
- [x] LTC: Art-Net time code display & controls
- [x] Win64 build
- [x] Android build
- [x] MacOS build 
- [x] Linux build
- [ ] Splash-screen and device icons

**Comment by hippyau** [comment]
Reading Art-Net Time Code from a device, with start/stop control...
![image](https://user-images.githubusercontent.com/36442309/134910860-3b06314d-f838-42f2-8c1a-5e553383ce4e.png)

**Comment by hippyau** [comment]
![ezgif-2-feeb9f119132](https://user-images.githubusercontent.com/36442309/135281645-6fb63853-92ae-4334-bee1-059a538871a6.gif)
